### ISSUE TITLE
OrderedMapIterator.pointer does not support array destructuring assignment (TypeError: it.pointer is not iterable)

### ISSUE THREAD

**Issue by x11x** [js-sdsl/js-sdsl#176]
**Describe the bug**
The value returned by `OrderedMapIterator#pointer` only supports access by index and does not implement iterable protocol, and hence you can't use it with destructuring assignment syntax.

I am working with `OrderedMap` but presumably the same problem applies to iterators for the other map collections.

**To Reproduce**
Given an `OrderedMapIterator`, `it`, which is not pointing to `end()` or `rEnd()`
(example setup code):
```js
const map = new OrderedMap();
map.setElement('a', 1);
map.setElement('c', 2);
const it = map.lowerBound('b'); // Will be pointing to key 'c'
```
```js
// Does not work:
const [key, value] = it.pointer; // Throws TypeError: it.pointer is not iterable
// Works:
const key = it.pointer[0];
const value = it.pointer[1];
```

**Expected behavior**
Array destructuring assignment is idiomatic so I think it would be expected to be able to do this.
The solution is to implement `Symbol.iterator` method on the `Proxy` object returned by `pointer`.
However, I would like to suggest a simpler solution, maybe we can just allow accessing by property names "key" and "value".
So we could do e.g.
```js
// ...
const {key, value} = it.pointer;
// Or if we want to assign different local variable names:
const {key: diffNameForKey, value: diffNameForValue} = it.pointer;
```

This would not be a breaking change as accessing by index could still be supported. For completeness, the iterable implementation is pretty simple and allows using the array destructuring syntax. (I can have a go at providing an implementation if you want). I wonder if it would be simpler to just return an array rather than use a `Proxy`, but I assume `Proxy` was chosen for a reason?

**Additional context**
This problem may not show up if transpiling to an older ES target, where destructuring assignment is transpiled to accessing by index syntax.

**Another idea for a solution**: I wonder if it would be a good idea to provide convenience property getters directly on the `OrderedMapIterator`? e.g. `it.key` and `it.value`.

**Comment by ZLY201** [comment]
Thanks for your feedback and suggestions, I will try to answer your questions.

**Why use `proxy`**
Because the 'value' (not the 'key' or 'value' but the value of iterator pointer) is dynamic which means it can be changed. In order to get the correct value each time it is accessed I must set a `proxy` to iterator.

```ts
const mp = new OrderedMap();
mp.set(0, 1);
cosnt it = mp.begin();
console.log(it.pointer[0], it.pointer[1]);  // 0 1
mp.set(0, 2);
console.log(it.pointer[0], it.pointer[1]);  // 0 2
```

**Why not `it.key` or `it.value`**
The iterators in this library are analogous to C++ pointers, but there are no pointers in Js as we all know. To simulate the operator `*` (Get the contents of the memory pointed to by the pointer) we add a property named `pointer` to `Iterator`.

In C++ code:

```c++
set<int> st { 1, 2 };
for (auto it = st.begin(); it != st.end(); ++it) {
  cout << *it << endl;  // 1, 2
}
```

For the other reason, if designed in`it.key/it.value` form, it will cause misunderstanding for the value of other non-dictionary container iterators.

**Why not `it.pointer.key/it.pointer.value`**

In fact, in earlier versions this was indeed the case. But for completeness of type definition (typescript), we need to define extra type for `key/value` of pointer.

```ts
type Pair<K, V> = {
  key: K;
  value: V;
}
```

And also need to change all the returned or template type to `K | Pair<K, V>`. This is completely unnecessary and inelegant to implement in my opinion. We can make it more simple by using `[K, V]`.

**To solve this problem**
Yeah, this is really a problem you cannot use destructuring assignment syntax for `iterator pointer`. All I can think of are the two solutions mentioned above:

1. Add `Symbol.iterator` function for `pointer` proxy (seems not good).
2. Change `iterator pointer` to `key/value` pair mode.

I will continue to think about this question, if there is no other solution, I may try to use the second solution in version 5.0.

**Comment by ZLY201** [comment]
New way found. See https://github.com/js-sdsl/js-sdsl/pull/178.

**Comment by ZLY201** [comment]
Version 4.4.2 has been published. @x11x
